# Generated by Django 5.2.7 on 2026-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_project_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='profile_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
