# Generated by Django 5.2.7 on 2026-03-16 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_user_created_at_user_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('auth_reset_request', 'Auth Reset Request'), ('auth_reset_approve', 'Auth Reset Approve'), ('auth_reset_reject', 'Auth Reset Reject'), ('user_create', 'User Create'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_submit', 'Project Submit'), ('project_approve', 'Project Approve'), ('project_reject', 'Project Reject'), ('project_archive', 'Project Archive')], max_length=40),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_ip', models.CharField(blank=True, max_length=64)),
                ('requested_user_agent', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
