# Generated by Django 5.2.7 on 2026-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_useractivity_event_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('auth_reset_request', 'Auth Reset Request'), ('auth_reset_approve', 'Auth Reset Approve'), ('auth_reset_reject', 'Auth Reset Reject'), ('user_create', 'User Create'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_submit', 'Project Submit'), ('project_approve', 'Project Approve'), ('project_reject', 'Project Reject'), ('project_archive', 'Project Archive'), ('validator_draft', 'Validator Draft'), ('validator_reviewed', 'Validator Reviewed'), ('validator_endorsed', 'Validator Endorsed')], max_length=40),
        ),
    ]
