# Generated by Django 5.2.7 on 2026-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_useractivity_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(default=0),
        ),
    ]
