# Generated by Django 5.2.7 on 2026-06-07 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_user_session_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('auth_reset_request', 'Auth Reset Request'), ('auth_reset_approve', 'Auth Reset Approve'), ('auth_reset_reject', 'Auth Reset Reject'), ('user_create', 'User Create'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_submit', 'Project Submit'), ('project_approve', 'Project Approve'), ('project_reject', 'Project Reject'), ('project_archive', 'Project Archive'), ('project_comment', 'Project Comment'), ('validator_draft', 'Validator Draft'), ('validator_reviewed', 'Validator Reviewed'), ('validator_endorsed', 'Validator Endorsed'), ('priority_analysis_run', 'Priority Analysis Run'), ('priority_analysis_reused', 'Priority Analysis Reused'), ('priority_analysis_confirmed', 'Priority Analysis Confirmed'), ('priority_analysis_overridden', 'Priority Analysis Overridden'), ('public_summary_overridden', 'Public Summary Overridden'), ('encoding_window_updated', 'Encoding Window Updated'), ('progress_window_updated', 'Progress Update Window Updated'), ('project_revision_created', 'Project Revision Created'), ('project_revision_updated', 'Project Revision Updated'), ('project_revision_submitted', 'Project Revision Submitted'), ('project_revision_reviewed', 'Project Revision Reviewed'), ('project_revision_endorsed', 'Project Revision Endorsed'), ('project_revision_rejected', 'Project Revision Rejected'), ('chat_knowledge_approved', 'Chat Knowledge Approved'), ('chat_knowledge_rejected', 'Chat Knowledge Rejected'), ('chat_content_updated', 'Chat Content Updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='PublicChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_normalized', models.CharField(db_index=True, max_length=255)),
                ('question_sample', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog')], default='en', max_length=10)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('answer_type', models.CharField(choices=[('direct', 'Direct Answer'), ('related', 'Possibly Related'), ('fallback', 'Fallback'), ('blocked', 'Blocked')], default='fallback', max_length=20)),
                ('feedback', models.CharField(blank=True, choices=[('', 'No Feedback'), ('up', 'Helpful'), ('down', 'Not Helpful')], default='', max_length=10)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('matched_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_interactions', to='projects.publiccontent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicChatKnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_normalized', models.CharField(max_length=255, unique=True)),
                ('question_sample', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('tl', 'Tagalog')], default='en', max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_asked', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('suggested_title', models.CharField(blank=True, max_length=200)),
                ('suggested_summary', models.TextField(blank=True)),
                ('suggested_body', models.TextField(blank=True)),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_chat_gaps', to='projects.publiccontent')),
                ('matched_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_gap_matches', to='projects.publiccontent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chat_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-count', '-last_asked'],
            },
        ),
    ]
