# Generated by Django 5.2.7 on 2026-06-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_useractivity_event_publicchatinteraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('auth_reset_request', 'Auth Reset Request'), ('auth_reset_approve', 'Auth Reset Approve'), ('auth_reset_reject', 'Auth Reset Reject'), ('user_create', 'User Create'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_submit', 'Project Submit'), ('project_approve', 'Project Approve'), ('project_reject', 'Project Reject'), ('project_archive', 'Project Archive'), ('project_comment', 'Project Comment'), ('validator_draft', 'Validator Draft'), ('validator_reviewed', 'Validator Reviewed'), ('validator_endorsed', 'Validator Endorsed'), ('priority_analysis_run', 'Priority Analysis Run'), ('priority_analysis_reused', 'Priority Analysis Reused'), ('priority_analysis_confirmed', 'Priority Analysis Confirmed'), ('priority_analysis_overridden', 'Priority Analysis Overridden'), ('public_summary_overridden', 'Public Summary Overridden'), ('encoding_window_updated', 'Encoding Window Updated'), ('progress_window_updated', 'Progress Update Window Updated'), ('project_revision_created', 'Project Revision Created'), ('project_revision_updated', 'Project Revision Updated'), ('project_revision_submitted', 'Project Revision Submitted'), ('project_revision_reviewed', 'Project Revision Reviewed'), ('project_revision_endorsed', 'Project Revision Endorsed'), ('project_revision_rejected', 'Project Revision Rejected'), ('cms_event_created', 'CMS Event Created'), ('cms_event_updated', 'CMS Event Updated'), ('cms_event_submitted', 'CMS Event Submitted'), ('cms_event_published', 'CMS Event Published'), ('cms_event_rejected', 'CMS Event Rejected'), ('cms_event_archived', 'CMS Event Archived'), ('chat_knowledge_approved', 'Chat Knowledge Approved'), ('chat_knowledge_rejected', 'Chat Knowledge Rejected'), ('chat_content_updated', 'Chat Content Updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('forum', 'Forum'), ('consultation', 'Consultation'), ('deadline', 'Deadline'), ('summit', 'Summit'), ('other', 'Other')], default='meeting', max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_virtual', models.BooleanField(default=False)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('review_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_events', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_events', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_public_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at', 'title'],
            },
        ),
    ]
