# Generated by Django 5.2.7 on 2026-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_useractivity_event_publicevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('validator', 'Validator'), ('staff', 'Staff'), ('content_editor', 'Content Editor')], max_length=20),
        ),
    ]
