from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0028_cms_v2_audit_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("auth_reset_request", "Auth Reset Request"),
                    ("auth_reset_approve", "Auth Reset Approve"),
                    ("auth_reset_reject", "Auth Reset Reject"),
                    ("user_create", "User Create"),
                    ("project_create", "Project Create"),
                    ("project_update", "Project Update"),
                    ("project_submit", "Project Submit"),
                    ("project_approve", "Project Approve"),
                    ("project_reject", "Project Reject"),
                    ("project_archive", "Project Archive"),
                    ("project_comment", "Project Comment"),
                    ("validator_draft", "Validator Draft"),
                    ("validator_reviewed", "Validator Reviewed"),
                    ("validator_endorsed", "Validator Endorsed"),
                    ("priority_analysis_run", "Priority Analysis Run"),
                    ("priority_analysis_reused", "Priority Analysis Reused"),
                    ("priority_analysis_confirmed", "Priority Analysis Confirmed"),
                    ("priority_analysis_overridden", "Priority Analysis Overridden"),
                    ("public_summary_overridden", "Public Summary Overridden"),
                    ("encoding_window_updated", "Encoding Window Updated"),
                    ("progress_window_updated", "Progress Update Window Updated"),
                    ("project_revision_created", "Project Revision Created"),
                    ("project_revision_updated", "Project Revision Updated"),
                    ("project_revision_submitted", "Project Revision Submitted"),
                    ("project_revision_reviewed", "Project Revision Reviewed"),
                    ("project_revision_endorsed", "Project Revision Endorsed"),
                    ("project_revision_rejected", "Project Revision Rejected"),
                    ("cms_event_created", "CMS Event Created"),
                    ("cms_event_updated", "CMS Event Updated"),
                    ("cms_event_submitted", "CMS Event Submitted"),
                    ("cms_event_published", "CMS Event Published"),
                    ("cms_event_rejected", "CMS Event Rejected"),
                    ("cms_event_archived", "CMS Event Archived"),
                    ("cms_event_unarchived", "CMS Event Unarchived"),
                    ("cms_content_created", "CMS Content Created"),
                    ("cms_content_updated", "CMS Content Updated"),
                    ("cms_content_submitted", "CMS Content Submitted"),
                    ("cms_content_published", "CMS Content Published"),
                    ("cms_content_rejected", "CMS Content Rejected"),
                    ("cms_content_archived", "CMS Content Archived"),
                    ("cms_content_restored", "CMS Content Restored"),
                    ("cms_section_lock_acquired", "CMS Section Lock Acquired"),
                    ("cms_section_lock_blocked", "CMS Section Lock Blocked"),
                    ("cms_section_lock_released", "CMS Section Lock Released"),
                    ("cms_section_access_requested", "CMS Section Access Requested"),
                    ("cms_chatbot_sync_failed", "CMS Chatbot Sync Failed"),
                    ("chat_knowledge_approved", "Chat Knowledge Approved"),
                    ("chat_knowledge_rejected", "Chat Knowledge Rejected"),
                    ("chat_content_updated", "Chat Content Updated"),
                ],
                max_length=40,
            ),
        ),
    ]
