# Generated by Django 5.2.7 on 2026-09-15 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_audit_snapshots(apps, schema_editor):
    Activity = apps.get_model('projects', 'UserActivity')
    fields = ['actor_username', 'actor_full_name', 'project_id_snapshot', 'project_title_snapshot']
    last_pk = 0
    while True:
        batch = list(
            Activity.objects.filter(pk__gt=last_pk)
            .select_related('user', 'project')
            .order_by('pk')[:500]
        )
        if not batch:
            break
        last_pk = batch[-1].pk
        for activity in batch:
            if activity.user_id:
                activity.actor_username = activity.user.username
                activity.actor_full_name = activity.user.full_name or activity.user.username
            if activity.project_id:
                activity.project_id_snapshot = activity.project_id
                activity.project_title_snapshot = activity.project.name
        Activity.objects.bulk_update(batch, fields, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_useractivity_cms_event_unarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='actor_full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='actor_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='project_id_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='project_title_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(backfill_audit_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='useractivity',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('auth_password_setup', 'Password Setup Completed'), ('auth_reset_request', 'Auth Reset Request'), ('auth_reset_approve', 'Auth Reset Approve'), ('auth_reset_reject', 'Auth Reset Reject'), ('user_create', 'User Create'), ('user_update', 'User Update'), ('user_status_changed', 'User Status Changed'), ('user_delete', 'User Delete'), ('project_create', 'Project Create'), ('project_update', 'Project Update'), ('project_delete', 'Project Delete'), ('project_submit', 'Project Submit'), ('project_approve', 'Project Approve'), ('project_reject', 'Project Reject'), ('project_archive', 'Project Archive'), ('project_comment', 'Project Comment'), ('validator_draft', 'Validator Draft'), ('validator_reviewed', 'Validator Reviewed'), ('validator_endorsed', 'Validator Endorsed'), ('priority_analysis_run', 'Priority Analysis Run'), ('priority_analysis_reused', 'Priority Analysis Reused'), ('priority_analysis_confirmed', 'Priority Analysis Confirmed'), ('priority_analysis_overridden', 'Priority Analysis Overridden'), ('public_summary_overridden', 'Public Summary Overridden'), ('encoding_window_updated', 'Encoding Window Updated'), ('progress_window_updated', 'Progress Update Window Updated'), ('project_revision_created', 'Project Revision Created'), ('project_revision_updated', 'Project Revision Updated'), ('project_revision_submitted', 'Project Revision Submitted'), ('project_revision_reviewed', 'Project Revision Reviewed'), ('project_revision_endorsed', 'Project Revision Endorsed'), ('project_revision_rejected', 'Project Revision Rejected'), ('cms_event_created', 'CMS Event Created'), ('cms_event_updated', 'CMS Event Updated'), ('cms_event_submitted', 'CMS Event Submitted'), ('cms_event_published', 'CMS Event Published'), ('cms_event_rejected', 'CMS Event Rejected'), ('cms_event_archived', 'CMS Event Archived'), ('cms_event_unarchived', 'CMS Event Unarchived'), ('cms_event_deleted', 'CMS Event Deleted'), ('cms_content_created', 'CMS Content Created'), ('cms_content_updated', 'CMS Content Updated'), ('cms_content_submitted', 'CMS Content Submitted'), ('cms_content_published', 'CMS Content Published'), ('cms_content_rejected', 'CMS Content Rejected'), ('cms_content_archived', 'CMS Content Archived'), ('cms_content_restored', 'CMS Content Restored'), ('cms_section_lock_acquired', 'CMS Section Lock Acquired'), ('cms_section_lock_blocked', 'CMS Section Lock Blocked'), ('cms_section_lock_released', 'CMS Section Lock Released'), ('cms_section_access_requested', 'CMS Section Access Requested'), ('cms_form_lock_acquired', 'CMS Form Lock Acquired'), ('cms_form_lock_blocked', 'CMS Form Lock Blocked'), ('cms_form_lock_released', 'CMS Form Lock Released'), ('cms_form_access_requested', 'CMS Form Access Requested'), ('notification_read', 'Notification Read'), ('notification_read_all', 'All Notifications Read'), ('access_request_approved', 'Access Request Approved'), ('access_request_rejected', 'Access Request Rejected'), ('api_action', 'API Action'), ('api_action_failed', 'API Action Failed'), ('cms_chatbot_sync_failed', 'CMS Chatbot Sync Failed'), ('chat_knowledge_approved', 'Chat Knowledge Approved'), ('chat_knowledge_rejected', 'Chat Knowledge Rejected'), ('chat_content_updated', 'Chat Content Updated')], max_length=40),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
