# Generated by Django 5.2.7 on 2026-06-12 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cms/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cms_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(default='Updates', max_length=80)),
                ('summary', models.CharField(blank=True, max_length=350)),
                ('body', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('has_unpublished_changes', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cms_articles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cms_articles', to=settings.AUTH_USER_MODEL)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_articles', to='cms.cmsmediaasset')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('has_unpublished_changes', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cms_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CMSPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(max_length=120)),
                ('section_type', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.cmspage')),
            ],
            options={
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('page', 'Page'), ('article', 'Article'), ('section', 'Section'), ('media', 'Media')], max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('version_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('publish', 'Publish'), ('archive', 'Archive'), ('reorder', 'Reorder')], max_length=20)),
                ('status_before', models.CharField(blank=True, max_length=40)),
                ('status_after', models.CharField(blank=True, max_length=40)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='cmsmediaasset',
            index=models.Index(fields=['file_type', 'is_archived'], name='cms_cmsmedi_file_ty_ee1701_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsmediaasset',
            index=models.Index(fields=['created_at'], name='cms_cmsmedi_created_bc8771_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsarticle',
            index=models.Index(fields=['slug'], name='cms_cmsarti_slug_8e4fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsarticle',
            index=models.Index(fields=['status', 'featured'], name='cms_cmsarti_status_a4102d_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsarticle',
            index=models.Index(fields=['category'], name='cms_cmsarti_categor_fe6ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsarticle',
            index=models.Index(fields=['has_unpublished_changes'], name='cms_cmsarti_has_unp_613615_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspage',
            index=models.Index(fields=['slug'], name='cms_cmspage_slug_285f25_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspage',
            index=models.Index(fields=['status'], name='cms_cmspage_status_219e45_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspage',
            index=models.Index(fields=['has_unpublished_changes'], name='cms_cmspage_has_unp_8ec481_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspagesection',
            index=models.Index(fields=['page', 'is_visible', 'order'], name='cms_cmspage_page_id_580b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='cmspagesection',
            index=models.Index(fields=['section_type'], name='cms_cmspage_section_c59344_idx'),
        ),
        migrations.AddConstraint(
            model_name='cmspagesection',
            constraint=models.UniqueConstraint(fields=('page', 'section_key'), name='unique_cms_section_key_per_page'),
        ),
        migrations.AddConstraint(
            model_name='cmspagesection',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='unique_cms_section_order_per_page'),
        ),
        migrations.AddIndex(
            model_name='cmsrevision',
            index=models.Index(fields=['content_type', 'object_id', '-version_number'], name='cms_cmsrevi_content_051b78_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsrevision',
            index=models.Index(fields=['action'], name='cms_cmsrevi_action_db8d0c_idx'),
        ),
        migrations.AddIndex(
            model_name='cmsrevision',
            index=models.Index(fields=['created_at'], name='cms_cmsrevi_created_3c2ba2_idx'),
        ),
        migrations.AddConstraint(
            model_name='cmsrevision',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'version_number'), name='unique_cms_revision_version_per_object'),
        ),
    ]
