// src/services/projectsData.ts
export type ProjectStatus = "ongoing" | "completed" | "proposed" | "planning";

export interface Project {
  id: number;
  title: string;
  status: ProjectStatus;
  agency?: string;
  budget: number; // in PHP (integer)
  startDate: string; // ISO date string
  endDate?: string;
  completion?: number; // 0-100
  description: string;
  year: number; // <-- added for filtering
  lgu?: string; // <-- added for LGU
  documents?: { name: string; url?: string }[];
}

export const projectsData: Project[] = [
  {
    id: 1,
    title: "Manila Bay Clean-Up",
    status: "ongoing",
    agency: "DENR",
    budget: 500000000,
    year: 2024,
    lgu: "Manila",
    description: "Ongoing rehabilitation and clean-up of Manila Bay.",
    completion: 60,
    startDate: "2024-01-10",
    documents: [],
  },
  {
    id: 2,
    title: "Quezon City Green Park",
    status: "completed",
    agency: "DPWH",
    budget: 200000000,
    year: 2023,
    lgu: "Quezon City",
    description: "Development of a new eco-friendly park in Quezon City.",
    completion: 100,
    startDate: "2023-02-15",
    endDate: "2023-12-20",
    documents: [],
  },
  {
    id: 3,
    title: "Pasig River Ferry Expansion",
    status: "proposed",
    agency: "MMDA",
    budget: 150000000,
    year: 2025,
    lgu: "Pasig",
    description: "Proposed expansion of ferry service in Pasig River.",
    completion: 0,
    startDate: "2025-03-01",
    documents: [],
  },
  {
    id: 4,
    title: "Makati Road Widening",
    status: "planning",
    agency: "DPWH",
    budget: 300000000,
    year: 2024,
    lgu: "Makati",
    description: "Planned road widening in Makati CBD.",
    completion: 0,
    startDate: "2024-05-01",
    documents: [],
  },
  {
    id: 5,
    title: "Caloocan Drainage Upgrade",
    status: "ongoing",
    agency: "DPWH",
    budget: 120000000,
    year: 2024,
    lgu: "Caloocan",
    description: "Ongoing drainage system upgrade in Caloocan.",
    completion: 40,
    startDate: "2024-02-10",
    documents: [],
  },
  {
    id: 6,
    title: "Taguig Hospital Construction",
    status: "completed",
    agency: "DOH",
    budget: 400000000,
    year: 2023,
    lgu: "Taguig",
    description: "Construction of a new hospital in Taguig.",
    completion: 100,
    startDate: "2022-08-01",
    endDate: "2023-09-30",
    documents: [],
  },
  {
    id: 7,
    title: "Pasay School Renovation",
    status: "proposed",
    agency: "DepEd",
    budget: 80000000,
    year: 2025,
    lgu: "Pasay",
    description: "Proposed renovation of public schools in Pasay.",
    completion: 0,
    startDate: "2025-06-01",
    documents: [],
  },
  {
    id: 8,
    title: "Parañaque Flood Control",
    status: "planning",
    agency: "DPWH",
    budget: 90000000,
    year: 2024,
    lgu: "Parañaque",
    description: "Flood control project for Parañaque.",
    completion: 0,
    startDate: "2024-07-01",
    documents: [],
  },
  {
    id: 9,
    title: "Las Piñas Health Center",
    status: "ongoing",
    agency: "DOH",
    budget: 60000000,
    year: 2024,
    lgu: "Las Piñas",
    description: "Construction of a new health center in Las Piñas.",
    completion: 30,
    startDate: "2024-03-15",
    documents: [],
  },
  {
    id: 10,
    title: "Mandaluyong Digital Hub",
    status: "completed",
    agency: "DICT",
    budget: 110000000,
    year: 2023,
    lgu: "Mandaluyong",
    description: "Completed digital hub for Mandaluyong residents.",
    completion: 100,
    startDate: "2022-11-01",
    endDate: "2023-10-15",
    documents: [],
  },
  {
    id: 11,
    title: "Marikina Riverbank Protection",
    status: "proposed",
    agency: "DENR",
    budget: 95000000,
    year: 2025,
    lgu: "Marikina",
    description: "Proposed riverbank protection project in Marikina.",
    completion: 0,
    startDate: "2025-04-01",
    documents: [],
  },
  {
    id: 12,
    title: "Muntinlupa Housing Project",
    status: "planning",
    agency: "NHA",
    budget: 250000000,
    year: 2024,
    lgu: "Muntinlupa",
    description: "Planned housing project for Muntinlupa residents.",
    completion: 0,
    startDate: "2024-09-01",
    documents: [],
  },
  {
    id: 13,
    title: "Navotas Fishing Port Upgrade",
    status: "ongoing",
    agency: "DA",
    budget: 70000000,
    year: 2024,
    lgu: "Navotas",
    description: "Upgrade of Navotas fishing port facilities.",
    completion: 55,
    startDate: "2024-02-20",
    documents: [],
  },
  {
    id: 14,
    title: "San Juan Sports Complex",
    status: "completed",
    agency: "DPWH",
    budget: 130000000,
    year: 2023,
    lgu: "San Juan",
    description: "New sports complex for San Juan City.",
    completion: 100,
    startDate: "2022-10-01",
    endDate: "2023-08-20",
    documents: [],
  },
  {
    id: 15,
    title: "Valenzuela Road Lighting",
    status: "proposed",
    agency: "DPWH",
    budget: 60000000,
    year: 2025,
    lgu: "Valenzuela",
    description: "Proposed road lighting project in Valenzuela.",
    completion: 0,
    startDate: "2025-05-01",
    documents: [],
  },
  {
    id: 16,
    title: "Malabon Drainage Project",
    status: "planning",
    agency: "DPWH",
    budget: 85000000,
    year: 2024,
    lgu: "Malabon",
    description: "Drainage improvement project for Malabon.",
    completion: 0,
    startDate: "2024-08-01",
    documents: [],
  },
  {
    id: 17,
    title: "Pateros Community Center",
    status: "ongoing",
    agency: "DSWD",
    budget: 50000000,
    year: 2024,
    lgu: "Pateros",
    description: "Construction of a new community center in Pateros.",
    completion: 20,
    startDate: "2024-04-01",
    documents: [],
  },
];
