# rdc_site/settings.py
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import sys
import secrets

# load .env from backend/.env if present
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Security and deployment-aware defaults
# Default `DEBUG` to False unless explicitly set to a truthy value in env.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Require SECRET_KEY in non-debug (production) environments.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Local development fallback (explicit and visible)
        SECRET_KEY = 'django-insecure-local-dev-key'
    else:
        # If running the development server via manage.py runserver, allow generating
        # a temporary secret to avoid developer friction. In production this will still
        # raise an error unless SECRET_KEY is provided in the environment.
        if any(arg.startswith('runserver') or arg == 'runserver' for arg in sys.argv):
            SECRET_KEY = secrets.token_urlsafe(50)
            # Print a clear warning so developers know this is temporary.
            print('\nWARNING: SECRET_KEY not set; using a temporary autogenerated key for runserver.\n')
        else:
            raise ImproperlyConfigured('The SECRET_KEY environment variable must be set in production')

# ALLOWED_HOSTS: when provided, split by comma; default to localhost in debug,
# otherwise default to an empty list to force explicit configuration in prod.
_allowed = os.environ.get('ALLOWED_HOSTS')
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if DEBUG else []

AUTH_USER_MODEL = 'projects.User'  # Or 'users.User' if you have users app

ROOT_URLCONF = "rdc_site.urls"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # Postgres-specific fields and functions
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'projects',  # Your app
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.environ.get('JWT_ACCESS_HOURS', '8'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Your React frontend
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

# Database configuration: prefer Postgres when env vars are present, otherwise use sqlite3 for local dev
# Allow forcing sqlite for one-off commands by setting FORCE_SQLITE=1 in the environment
if os.environ.get('FORCE_SQLITE', '').lower() in ('1', 'true', 'yes'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER', ''),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }

# Connection pooling and transactional requests
CONN_MAX_AGE = int(os.environ.get('CONN_MAX_AGE', 600))
DATABASES['default']['CONN_MAX_AGE'] = CONN_MAX_AGE
DATABASES['default']['ATOMIC_REQUESTS'] = True

# Security: require SSL in production-managed DBs when provided
DB_SSLMODE = os.environ.get('POSTGRES_SSLMODE')
if DB_SSLMODE and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {'sslmode': DB_SSLMODE}

# Minimal middleware and templates required for admin and management commands
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
# Minimal defaults for development; adjust STATIC_ROOT for production collectstatic.
STATIC_URL = os.environ.get('STATIC_URL', '/static/')
try:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STATICFILES_DIRS = [BASE_DIR / 'static']
except Exception:
    STATIC_ROOT = str(BASE_DIR / 'staticfiles')
    STATICFILES_DIRS = [str(BASE_DIR / 'static')]

# Email (SMTP)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@rdc-portal.local")
CONTACT_RECEIVER_EMAIL = os.environ.get("CONTACT_RECEIVER_EMAIL", "ian095108@gmail.com")

# Frontend base URL for setup links
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")

# Password reset request protections
PASSWORD_RESET_RATE_LIMIT_WINDOW = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_WINDOW", "3600"))
PASSWORD_RESET_RATE_LIMIT_EMAIL = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_EMAIL", "2"))
PASSWORD_RESET_RATE_LIMIT_IP = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_IP", "5"))

# Cloudflare Turnstile CAPTCHA (optional)
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "")
TURNSTILE_REQUIRED = os.environ.get("TURNSTILE_REQUIRED", "false").lower() in ("1", "true", "yes")

# Sentry configuration (optional)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.0')),
            send_default_pii=os.environ.get('SENTRY_SEND_PII', 'false').lower() in ('1', 'true', 'yes'),
        )
    except Exception:
        # Don't crash on misconfigured Sentry in environments where it's not available
        pass
