# rdc_site/settings.py
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import sys
import secrets

try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# load .env from backend/.env if present
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def env_int(name, default=0):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


def env_list(name, default=None):
    raw = os.environ.get(name)
    if raw is None:
        return list(default or [])
    return [item.strip() for item in raw.split(',') if item.strip()]

# Security and deployment-aware defaults
# Default `DEBUG` to False unless explicitly set to a truthy value in env.
DEBUG = env_bool('DEBUG', False)

# Require SECRET_KEY in non-debug (production) environments.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Local development fallback (explicit and visible)
        SECRET_KEY = 'django-insecure-local-dev-key'
    else:
        # If running the development server via manage.py runserver, allow generating
        # a temporary secret to avoid developer friction. In production this will still
        # raise an error unless SECRET_KEY is provided in the environment.
        if any(arg.startswith('runserver') or arg == 'runserver' for arg in sys.argv):
            SECRET_KEY = secrets.token_urlsafe(50)
            # Print a clear warning so developers know this is temporary.
            print('\nWARNING: SECRET_KEY not set; using a temporary autogenerated key for runserver.\n')
        else:
            raise ImproperlyConfigured('The SECRET_KEY environment variable must be set in production')

# ALLOWED_HOSTS: when provided, split by comma; default to localhost in debug,
# otherwise default to an empty list to force explicit configuration in prod.
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'] if DEBUG else [])

AUTH_USER_MODEL = 'projects.User'  # Or 'users.User' if you have users app

ROOT_URLCONF = "rdc_site.urls"

# RDC-NCR schedules are administered and displayed in Philippine Standard Time.
TIME_ZONE = "Asia/Manila"
USE_TZ = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # Postgres-specific fields and functions
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'cms',
    'projects',  # Your app
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'projects.authentication.SessionVersionJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.environ.get('JWT_ACCESS_HOURS', '8'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'TOKEN_REFRESH_SERIALIZER': 'projects.authentication.SessionVersionTokenRefreshSerializer',
}

# CORS / CSRF settings
CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    ['http://localhost:5173', 'http://localhost:3000'] if DEBUG else [],
)
CORS_ALLOW_CREDENTIALS = env_bool('CORS_ALLOW_CREDENTIALS', True)
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', CORS_ALLOWED_ORIGINS)

# Database configuration: prefer Postgres when env vars are present, otherwise use sqlite3 for local dev
# Allow forcing sqlite for one-off commands by setting FORCE_SQLITE=1 in the environment
DATABASE_URL = os.environ.get('DATABASE_URL', '')
if os.environ.get('FORCE_SQLITE', '').lower() in ('1', 'true', 'yes'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
elif DATABASE_URL:
    if dj_database_url is None:
        raise ImproperlyConfigured('DATABASE_URL requires dj-database-url to be installed')
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=env_int('CONN_MAX_AGE', 600),
            ssl_require=env_bool('DATABASE_SSL_REQUIRE', True),
        )
    }
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER', ''),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }

# Connection pooling and transactional requests
CONN_MAX_AGE = int(os.environ.get('CONN_MAX_AGE', 600))
DATABASES['default']['CONN_MAX_AGE'] = CONN_MAX_AGE
DATABASES['default']['ATOMIC_REQUESTS'] = True

# Security: require SSL for managed Postgres providers such as Supabase.
DB_SSLMODE = os.environ.get('POSTGRES_SSLMODE')
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    ssl_required = env_bool('DATABASE_SSL_REQUIRE', bool(DATABASE_URL))
    sslmode = 'require' if ssl_required else (DB_SSLMODE or '')
    if sslmode:
        DATABASES['default'].setdefault('OPTIONS', {})
        DATABASES['default']['OPTIONS']['sslmode'] = sslmode

# Minimal middleware and templates required for admin and management commands
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
# Minimal defaults for development; adjust STATIC_ROOT for production collectstatic.
STATIC_URL = os.environ.get('STATIC_URL', '/static/')
try:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STATICFILES_DIRS = [BASE_DIR / 'static']
except Exception:
    STATIC_ROOT = str(BASE_DIR / 'staticfiles')
    STATICFILES_DIRS = [str(BASE_DIR / 'static')]

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# CMS media uploads. Local development uses backend/media; production can replace
# storage later without changing the CMS API contract.
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
CMS_MAX_UPLOAD_BYTES = env_int('CMS_MAX_UPLOAD_BYTES', 10 * 1024 * 1024)

# Production security toggles. Enable these in Render once HTTPS domains are set.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')
if env_bool('SECURE_PROXY_SSL_HEADER', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Email (SMTP)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@rdc-portal.local")
CONTACT_RECEIVER_EMAIL = os.environ.get("CONTACT_RECEIVER_EMAIL", "ian095108@gmail.com")

# Frontend base URL for setup links
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")

# Password reset request protections
PASSWORD_RESET_RATE_LIMIT_WINDOW = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_WINDOW", "3600"))
PASSWORD_RESET_RATE_LIMIT_EMAIL = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_EMAIL", "2"))
PASSWORD_RESET_RATE_LIMIT_IP = int(os.environ.get("PASSWORD_RESET_RATE_LIMIT_IP", "5"))

# Cloudflare Turnstile CAPTCHA (optional)
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY", "")
TURNSTILE_REQUIRED = os.environ.get("TURNSTILE_REQUIRED", "false").lower() in ("1", "true", "yes")

# Sentry configuration (optional)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.0')),
            send_default_pii=os.environ.get('SENTRY_SEND_PII', 'false').lower() in ('1', 'true', 'yes'),
        )
    except Exception:
        # Don't crash on misconfigured Sentry in environments where it's not available
        pass
